# Generated by Django 5.0.6 on 2025-07-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('english_name', models.CharField(blank=True, max_length=500, null=True)),
                ('other_name', models.CharField(blank=True, max_length=500, null=True)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('genres', models.TextField()),
                ('synopsis', models.TextField()),
                ('Type', models.CharField(max_length=100)),
                ('episodes', models.CharField(max_length=50)),
                ('aired', models.CharField(max_length=200)),
                ('premiered', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('producers', models.TextField(blank=True, null=True)),
                ('licensors', models.TextField(blank=True, null=True)),
                ('studios', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('popularity', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('scored_by', models.CharField(max_length=50)),
                ('members', models.IntegerField()),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['popularity'],
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
