# Generated by Django 5.0.6 on 2025-07-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_anime_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='updated_at',
        ),
    ]
